export const reservations = [
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    spaceId: "A101",
    reservationId: "RES123456",
    startDateAndTime: "2023-10-01T10:00:00Z",
    requestTime: "2023-10-01T10:00:00Z",
    endDateAndTime: "2023-10-01T12:00:00Z",
    status: "confirmed",
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    spaceId: "B202",
    reservationId: "RES123457",
    startDateAndTime: "2023-10-02T14:00:00Z",
    requestTime: "2023-10-02T14:00:00Z",
    endDateAndTime: "2023-10-02T16:00:00Z",
    status: "pending",
  },
  {
    id: 3,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    spaceId: "C303",
    reservationId: "RES123458",
    startDateAndTime: "2023-10-03T09:00:00Z",
    requestTime: "2023-10-03T09:00:00Z",
    endDateAndTime: "2023-10-03T11:00:00Z",
    status: "canceled",
  },
  {
    id: 4,
    name: "Bob Brown",
    email: "bob.brown@example.com",
    spaceId: "D404",
    reservationId: "RES123459",
    startDateAndTime: "2023-10-04T13:00:00Z",
    requestTime: "2023-10-04T13:00:00Z",
    endDateAndTime: "2023-10-04T15:00:00Z",
    status: "confirmed",
  },
];

export const usersData = [
  {
    id: 1,
    sno: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    password: "password123",
    phoneNumber: "1234567890",
    noOfReservations: 5,
    noOfSpaces: 3,
    active: true,
  },
  {
    id: 2,
    sno: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    password: "password456",
    phoneNumber: "0987654321",
    noOfReservations: 2,
    noOfSpaces: 1,
    active: false,
  },
  {
    id: 3,
    sno: 3,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    password: "password789",
    phoneNumber: "5551234567",
    noOfReservations: 10,
    noOfSpaces: 5,
    active: true,
  },
  {
    id: 4,
    sno: 4,
    name: "Bob Brown",
    email: "bob.brown@example.com",
    password: "password101",
    phoneNumber: "5557654321",
    noOfReservations: 0,
    noOfSpaces: 2,
    active: true,
  },
  {
    id: 5,
    sno: 5,
    name: "Charlie Black",
    email: "charlie.black@example.com",
    password: "password202",
    phoneNumber: "5559876543",
    noOfReservations: 3,
    noOfSpaces: 4,
    active: false,
  },
  {
    id: 6,
    sno: 6,
    name: "Diana White",
    email: "diana.white@example.com",
    password: "password303",
    phoneNumber: "5556543210",
    noOfReservations: 1,
    noOfSpaces: 3,
    active: true,
  },
  {
    id: 7,
    sno: 7,
    name: "Ethan Green",
    email: "ethan.green@example.com",
    password: "password404",
    phoneNumber: "5553210987",
    noOfReservations: 4,
    noOfSpaces: 2,
    active: true,
  },
  {
    id: 8,
    sno: 8,
    name: "Fiona Blue",
    email: "fiona.blue@example.com",
    password: "password505",
    phoneNumber: "5557890123",
    noOfReservations: 6,
    noOfSpaces: 1,
    active: false,
  },
];
export const spaces = [
  {
    id: 1000,
    name: "James Butt",
    country: {
      name: "Algeria",
      code: "dz",
    },
    company: "Benton, John B Jr",
    date: "2015-09-13",
    status: "active",
    CompletedRequests: 12,
    rating: 3.5,
    representative: {
      name: "Ioni Bowcher",
      image: "ionibowcher.png",
    },
    balance: 70663,
  },
  {
    id: 1001,
    name: "Josephine Darakjy",
    country: {
      name: "Egypt",
      code: "eg",
    },
    company: "Chanay, Jeffrey A Esq",
    date: "2019-02-09",
    status: "deactiveted",
    CompletedRequests: 112,
    rating: 3.5,
    representative: {
      name: "Amy Elsner",
      image: "amyelsner.png",
    },
    balance: 82429,
  },
  {
    id: 1002,
    name: "Art Venere",
    country: {
      name: "Panama",
      code: "pa",
    },
    company: "Chemel, James L Cpa",
    date: "2017-05-13",
    status: "deactiveted",
    CompletedRequests: 2,
    rating: 3.5,
    representative: {
      name: "Asiya Javayant",
      image: "asiyajavayant.png",
    },
    balance: 28334,
  },
  {
    id: 1003,
    name: "Lenna Paprocki",
    country: {
      name: "Slovenia",
      code: "si",
    },
    company: "Feltz Printing Service",
    date: "2020-09-15",
    status: "active",
    CompletedRequests: 10,
    rating: 3.5,
    representative: {
      name: "Xuxue Feng",
      image: "xuxuefeng.png",
    },
    balance: 88521,
  },
  {
    id: 1004,
    name: "Donette Foller",
    country: {
      name: "South Africa",
      code: "za",
    },
    company: "Printing Dimensions",
    date: "2016-05-20",
    status: "deactiveted",
    verified: true,
    rating: 3.5,
    representative: {
      name: "Asiya Javayant",
      image: "asiyajavayant.png",
    },
    balance: 93905,
  },
  {
    id: 1005,
    name: "Simona Morasca",
    country: {
      name: "Egypt",
      code: "eg",
    },
    company: "Chapman, Ross E Esq",
    date: "2018-02-16",
    status: "active",
    verified: false,
    activity: 68,
    representative: {
      name: "Ivan Magalhaes",
      image: "ivanmagalhaes.png",
    },
    balance: 50041,
  },
];
